/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Path;

import spark.Spark;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
       Spark.get("/ZHAWDevops",(req, res) -> {
           return "Hello World";
       });
    }
}
